image: armv7/armhf-ubuntu
before_script:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install -y elixir erlang-ssl erlang-inets
  - mix local.hex --force
  - mix deps.get
stages:
  - check_style
  - test
  - coverage
  - build

test:
  stage: test
  script:
    - mix test

check_style:
  stage: check_style
  allow_failure: true
  script:
    - mix credo
    - mix dogma

coveralls:
  stage: coverage
  allow_failure: true
  script:
    - mix coveralls

build:
  script: mix escript.build
  artifacts:
    paths:
      - build
