image: elixir:1.3.4
before_script:
  - mix deps.get
stages:
  - check_style
  - test
  - coverage
  - build

test:
  stage: test
  script:
    - mix test

check_style:
  stage: check_style
  allow_failure: true
  script:
    - mix credo
    - mix dogma

coveralls:
  stage: coverage
  allow_failure: true
  script:
    - mix coveralls

build:
  script: mix escript.build
  artifacts:
    paths:
      - build
