defmodule TesslaServer.SpecProcessor do
  @moduledoc """
  Entry point for processing a Tessla Spec generated by the Tessla Compiler
  """

  alias TesslaServer.SpecProcessor.GraphBuilder

  @spec process(String.t) :: [integer]
  def process(spec) do
    json = Poison.decode! spec, keys: :atoms
    GraphBuilder.build json[:"items"]
  end
end
